# Site settings
title:       "SecTalks - Monthly technical (in)security talks and hands-on CTF"
email:       "guru@sectalks.org"
author:      "SecTalks Founder"
description: "Monthly technical (in)security talks and hands-on CTF, no bullshit!"
baseurl:     ""
url:         "https://www.sectalks.org"
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

twitter:
  username: sectalks
  card: summary
logo: /images/logo.png

date_format: "%-d %b %Y"

# Google analytics
google_analytics:

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
show_social_icons: true
github_username: sectalks
irc_server: "irc://chat.freenode.com:+7000/##sectalks"
twitter_username: sectalks
linkedin_username: sectalks
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: false
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: false
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

# Build settings
#markdown:     redcarpet
#redcarpet:
#  extensions: ['smart', 'tables', 'with_toc_data']
markdown: kramdown
permalink:    pretty
paginate:     5
paginate_path: "/blog/page:num/"
sass:
  compressed: true
  cache_location: /tmp/_site
